data <- read.table("household_power_consumption.txt" , header = TRUE, sep = ";" , stringsAsFactors = FALSE, dec = ".")
subsetdata <- data[data$Date %in% c("1/2/2007","2/2/2007"),]
datetime <- strptime(paste(subsetdata$Date,subsetdata$Time,sep = " "), "%d/%m/%Y %H:%M:%S")
GlobalActivePower <- as.numeric(subsetdata$Global_active_power)
Sub_metering_1 <- as.numeric(subsetdata$Sub_metering_1)
Sub_metering_2 <- as.numeric(subsetdata$Sub_metering_2)
Sub_metering_3 <- as.numeric(subsetdata$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(datetime,Sub_metering_1,type = "l", xlab = "",ylab = "Energy sub metering")
lines(datetime,Sub_metering_2, type = "l", col = "red")
lines(datetime,Sub_metering_3,type = "l", col = "blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = 1,lwd = 2.5,col = c("black","red","blue"))
dev.off()